[2020-07-18 17:28:58,026] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: etl_preprocessing.feature_selection_web 2020-07-18T21:27:31.188247+00:00 [queued]>
[2020-07-18 17:28:58,035] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: etl_preprocessing.feature_selection_web 2020-07-18T21:27:31.188247+00:00 [queued]>
[2020-07-18 17:28:58,036] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-07-18 17:28:58,036] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-07-18 17:28:58,036] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-07-18 17:28:58,041] {taskinstance.py:901} INFO - Executing <Task(DockerOperator): feature_selection_web> on 2020-07-18T21:27:31.188247+00:00
[2020-07-18 17:28:58,043] {standard_task_runner.py:54} INFO - Started process 45942 to run task
[2020-07-18 17:28:58,074] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'etl_preprocessing', 'feature_selection_web', '2020-07-18T21:27:31.188247+00:00', '--job_id', '70', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/elt_preprocessing.py', '--cfg_path', '/var/folders/00/80wjhvv115lcj4bckmhhb8x40000gn/T/tmp509jmbl_']
[2020-07-18 17:28:58,075] {standard_task_runner.py:78} INFO - Job 70: Subtask feature_selection_web
[2020-07-18 17:28:58,100] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: etl_preprocessing.feature_selection_web 2020-07-18T21:27:31.188247+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-07-18 17:28:58,243] {docker_operator.py:210} INFO - Starting docker container from image feature_selection_web:latest
[2020-07-18 17:28:58,847] {docker_operator.py:243} INFO - Input Notebook:  notebooks/feature_selection.ipynb
Output Notebook: notebooks/output/code_exec_111111.ipynb
[2020-07-18 17:28:59,782] {docker_operator.py:243} INFO - Executing notebook with kernel: venv-kensho-feature-selection
Executing Cell 1---------------------------------------
[2020-07-18 17:28:59,805] {docker_operator.py:243} INFO - Ending Cell 1------------------------------------------
[2020-07-18 17:28:59,817] {docker_operator.py:243} INFO - Executing Cell 2---------------------------------------
[2020-07-18 17:28:59,837] {docker_operator.py:243} INFO - name of the variable:docker.for.mac.host.internal
[2020-07-18 17:28:59,838] {docker_operator.py:243} INFO - Ending Cell 2------------------------------------------
[2020-07-18 17:28:59,850] {docker_operator.py:243} INFO - Executing Cell 3---------------------------------------
[2020-07-18 17:28:59,861] {docker_operator.py:243} INFO - Ending Cell 3------------------------------------------
[2020-07-18 17:28:59,874] {docker_operator.py:243} INFO - Executing Cell 4---------------------------------------
[2020-07-18 17:28:59,898] {docker_operator.py:243} INFO - '/'
[2020-07-18 17:28:59,901] {docker_operator.py:243} INFO - Ending Cell 4------------------------------------------
[2020-07-18 17:28:59,914] {docker_operator.py:243} INFO - Executing Cell 5---------------------------------------
[2020-07-18 17:28:59,926] {docker_operator.py:243} INFO - Ending Cell 5------------------------------------------
[2020-07-18 17:28:59,939] {docker_operator.py:243} INFO - Executing Cell 6---------------------------------------
[2020-07-18 17:28:59,951] {docker_operator.py:243} INFO - Ending Cell 6------------------------------------------
[2020-07-18 17:28:59,963] {docker_operator.py:243} INFO - Executing Cell 7---------------------------------------
[2020-07-18 17:29:00,642] {docker_operator.py:243} INFO - Ending Cell 7------------------------------------------
[2020-07-18 17:29:00,654] {docker_operator.py:243} INFO - Executing Cell 8---------------------------------------
[2020-07-18 17:29:00,668] {docker_operator.py:243} INFO - Ending Cell 8------------------------------------------
[2020-07-18 17:29:00,680] {docker_operator.py:243} INFO - Executing Cell 9---------------------------------------
[2020-07-18 17:29:00,705] {docker_operator.py:243} INFO - Ending Cell 9------------------------------------------
[2020-07-18 17:29:00,718] {docker_operator.py:243} INFO - Executing Cell 10--------------------------------------
[2020-07-18 17:29:00,731] {docker_operator.py:243} INFO - Ending Cell 10-----------------------------------------
[2020-07-18 17:29:00,744] {docker_operator.py:243} INFO - Executing Cell 11--------------------------------------
[2020-07-18 17:29:01,266] {docker_operator.py:243} INFO - docker.for.mac.host.internal
[2020-07-18 17:29:01,373] {docker_operator.py:243} INFO - Ending Cell 11-----------------------------------------
[2020-07-18 17:29:01,386] {docker_operator.py:243} INFO - Executing Cell 12--------------------------------------
[2020-07-18 17:29:01,398] {docker_operator.py:243} INFO - Ending Cell 12-----------------------------------------
[2020-07-18 17:29:01,411] {docker_operator.py:243} INFO - Executing Cell 13--------------------------------------
[2020-07-18 17:29:01,452] {docker_operator.py:243} INFO - name of the variable inside function:docker.for.mac.host.internal
[2020-07-18 17:29:01,454] {docker_operator.py:243} INFO - Ending Cell 13-----------------------------------------
[2020-07-18 17:29:01,469] {docker_operator.py:243} INFO - Executing Cell 14--------------------------------------
[2020-07-18 17:29:01,482] {docker_operator.py:243} INFO - Ending Cell 14-----------------------------------------
[2020-07-18 17:29:01,495] {docker_operator.py:243} INFO - Executing Cell 15--------------------------------------
[2020-07-18 17:29:01,556] {docker_operator.py:243} INFO - Ending Cell 15-----------------------------------------
[2020-07-18 17:29:01,570] {docker_operator.py:243} INFO - Executing Cell 16--------------------------------------
[2020-07-18 17:29:01,594] {docker_operator.py:243} INFO - Ending Cell 16-----------------------------------------
[2020-07-18 17:29:01,608] {docker_operator.py:243} INFO - Executing Cell 17--------------------------------------
[2020-07-18 17:29:01,740] {docker_operator.py:243} INFO - Ending Cell 17-----------------------------------------
[2020-07-18 17:29:02,184] {docker_operator.py:243} INFO - Traceback (most recent call last):
  File "/usr/local/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/papermill/cli.py", line 238, in papermill
    execution_timeout=execution_timeout,
  File "/usr/local/lib/python3.7/site-packages/papermill/execute.py", line 110, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/usr/local/lib/python3.7/site-packages/papermill/execute.py", line 222, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [10]":
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-10-576c88a4c92f> in <module>
     12         pickle.dump(le,handle,protocol=pickle.HIGHEST_PROTOCOL)
     13 elif opt=='test':
---> 14     with open(path+'label_encoder.p','rb') as handle:
     15         le = pickle.load(handle)
     16     l=le.transform(labels)

FileNotFoundError: [Errno 2] No such file or directory: '//notebooks/label_encoder.p'
[2020-07-18 17:29:02,433] {taskinstance.py:1150} ERROR - docker container failed: {'Error': None, 'StatusCode': 1}
Traceback (most recent call last):
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/site-packages/airflow/operators/docker_operator.py", line 277, in execute
    return self._run_image()
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/site-packages/airflow/operators/docker_operator.py", line 247, in _run_image
    raise AirflowException('docker container failed: ' + repr(result))
airflow.exceptions.AirflowException: docker container failed: {'Error': None, 'StatusCode': 1}
[2020-07-18 17:29:02,436] {taskinstance.py:1194} INFO - Marking task as FAILED. dag_id=etl_preprocessing, task_id=feature_selection_web, execution_date=20200718T212731, start_date=20200718T212858, end_date=20200718T212902
[2020-07-18 17:29:02,444] {configuration.py:338} WARNING - section/key [smtp/smtp_user] not found in config
[2020-07-18 17:29:02,446] {configuration.py:338} WARNING - section/key [smtp/smtp_user] not found in config
[2020-07-18 17:29:02,446] {taskinstance.py:1200} ERROR - Failed to send email to: ['info@example.com']
[2020-07-18 17:29:02,447] {taskinstance.py:1201} ERROR - [Errno 61] Connection refused
Traceback (most recent call last):
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/site-packages/airflow/operators/docker_operator.py", line 277, in execute
    return self._run_image()
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/site-packages/airflow/operators/docker_operator.py", line 247, in _run_image
    raise AirflowException('docker container failed: ' + repr(result))
airflow.exceptions.AirflowException: docker container failed: {'Error': None, 'StatusCode': 1}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1473, in email_alert
    send_email(self.task.email, subject, html_content)
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/site-packages/airflow/utils/email.py", line 62, in send_email
    mime_subtype=mime_subtype, mime_charset=mime_charset, **kwargs)
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/site-packages/airflow/utils/email.py", line 108, in send_email_smtp
    send_MIME_email(smtp_mail_from, recipients, msg, dryrun)
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/site-packages/airflow/utils/email.py", line 127, in send_MIME_email
    s = smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT) if SMTP_SSL else smtplib.SMTP(SMTP_HOST, SMTP_PORT)
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1198, in handle_failure
    self.email_alert(error)
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1475, in email_alert
    send_email(self.task.email, subject, html_content_err)
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/site-packages/airflow/utils/email.py", line 62, in send_email
    mime_subtype=mime_subtype, mime_charset=mime_charset, **kwargs)
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/site-packages/airflow/utils/email.py", line 108, in send_email_smtp
    send_MIME_email(smtp_mail_from, recipients, msg, dryrun)
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/site-packages/airflow/utils/email.py", line 127, in send_MIME_email
    s = smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT) if SMTP_SSL else smtplib.SMTP(SMTP_HOST, SMTP_PORT)
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/Users/mendes/miniconda3/envs/venv-kensho/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
[2020-07-18 17:29:03,023] {local_task_job.py:102} INFO - Task exited with return code 1
